# encoding: utf-8

import re


def kana_to_rime_code(string: str):
    string = string.replace('ー', '--')
    string = string.replace('あ', 'qa')
    string = string.replace('い', 'qi')
    string = string.replace('う', 'qu')
    string = string.replace('え', 'qe')
    string = string.replace('お', 'qo')
    string = string.replace('ゔ', 'vu')
    string = string.replace('か', 'ka')
    string = string.replace('き', 'ki')
    string = string.replace('く', 'ku')
    string = string.replace('け', 'ke')
    string = string.replace('こ', 'ko')
    string = string.replace('が', 'ga')
    string = string.replace('ぎ', 'gi')
    string = string.replace('ぐ', 'gu')
    string = string.replace('げ', 'ge')
    string = string.replace('ご', 'go')
    string = string.replace('さ', 'sa')
    string = string.replace('し', 'si')
    string = string.replace('す', 'su')
    string = string.replace('せ', 'se')
    string = string.replace('そ', 'so')
    string = string.replace('ざ', 'za')
    string = string.replace('じ', 'zi')
    string = string.replace('ず', 'zu')
    string = string.replace('ぜ', 'ze')
    string = string.replace('ぞ', 'zo')
    string = string.replace('た', 'ta')
    string = string.replace('ち', 'ti')
    string = string.replace('つ', 'tu')
    string = string.replace('て', 'te')
    string = string.replace('と', 'to')
    string = string.replace('だ', 'da')
    string = string.replace('ぢ', 'di')
    string = string.replace('づ', 'du')
    string = string.replace('で', 'de')
    string = string.replace('ど', 'do')
    string = string.replace('な', 'na')
    string = string.replace('に', 'ni')
    string = string.replace('ぬ', 'nu')
    string = string.replace('ね', 'ne')
    string = string.replace('の', 'no')
    string = string.replace('は', 'ha')
    string = string.replace('ひ', 'hi')
    string = string.replace('ふ', 'hu')
    string = string.replace('へ', 'he')
    string = string.replace('ほ', 'ho')
    string = string.replace('ば', 'ba')
    string = string.replace('び', 'bi')
    string = string.replace('ぶ', 'bu')
    string = string.replace('べ', 'be')
    string = string.replace('ぼ', 'bo')
    string = string.replace('ぱ', 'pa')
    string = string.replace('ぴ', 'pi')
    string = string.replace('ぷ', 'pu')
    string = string.replace('ぺ', 'pe')
    string = string.replace('ぽ', 'po')
    string = string.replace('ま', 'ma')
    string = string.replace('み', 'mi')
    string = string.replace('む', 'mu')
    string = string.replace('め', 'me')
    string = string.replace('も', 'mo')
    string = string.replace('や', 'ya')
    string = string.replace('ゆ', 'yu')
    string = string.replace('よ', 'yo')
    string = string.replace('ら', 'ra')
    string = string.replace('り', 'ri')
    string = string.replace('る', 'ru')
    string = string.replace('れ', 're')
    string = string.replace('ろ', 'ro')
    string = string.replace('わ', 'wa')
    string = string.replace('ゐ', 'wi')
    string = string.replace('ゑ', 'we')
    string = string.replace('を', 'wo')
    string = string.replace('ん', 'nn')
    string = string.replace('ぁ', 'xa')
    string = string.replace('ぃ', 'xi')
    string = string.replace('ぅ', 'xu')
    string = string.replace('ぇ', 'xe')
    string = string.replace('ぉ', 'xo')
    string = string.replace('ゃ', 'la')
    string = string.replace('ゅ', 'lu')
    string = string.replace('ょ', 'lo')
    string = string.replace('ゎ', 'va')
    string = string.replace('ゕ', 'ka')
    string = string.replace('ゖ', 'ke')
    string = string.replace('っ', 'xx')
    string = string.replace('ア', 'qa')
    string = string.replace('イ', 'qi')
    string = string.replace('ウ', 'qu')
    string = string.replace('エ', 'qe')
    string = string.replace('オ', 'qo')
    string = string.replace('ヴ', 'vu')
    string = string.replace('カ', 'ka')
    string = string.replace('キ', 'ki')
    string = string.replace('ク', 'ku')
    string = string.replace('ケ', 'ke')
    string = string.replace('コ', 'ko')
    string = string.replace('ガ', 'ga')
    string = string.replace('ギ', 'gi')
    string = string.replace('グ', 'gu')
    string = string.replace('ゲ', 'ge')
    string = string.replace('ゴ', 'go')
    string = string.replace('サ', 'sa')
    string = string.replace('シ', 'si')
    string = string.replace('ス', 'su')
    string = string.replace('セ', 'se')
    string = string.replace('ソ', 'so')
    string = string.replace('ザ', 'za')
    string = string.replace('ジ', 'zi')
    string = string.replace('ズ', 'zu')
    string = string.replace('ゼ', 'ze')
    string = string.replace('ゾ', 'zo')
    string = string.replace('タ', 'ta')
    string = string.replace('チ', 'ti')
    string = string.replace('ツ', 'tu')
    string = string.replace('テ', 'te')
    string = string.replace('ト', 'to')
    string = string.replace('ダ', 'da')
    string = string.replace('ヂ', 'di')
    string = string.replace('ヅ', 'du')
    string = string.replace('デ', 'de')
    string = string.replace('ド', 'do')
    string = string.replace('ナ', 'na')
    string = string.replace('ニ', 'ni')
    string = string.replace('ヌ', 'nu')
    string = string.replace('ネ', 'ne')
    string = string.replace('ノ', 'no')
    string = string.replace('ハ', 'ha')
    string = string.replace('ヒ', 'hi')
    string = string.replace('フ', 'hu')
    string = string.replace('ヘ', 'he')
    string = string.replace('ホ', 'ho')
    string = string.replace('バ', 'ba')
    string = string.replace('ビ', 'bi')
    string = string.replace('ブ', 'bu')
    string = string.replace('ベ', 'be')
    string = string.replace('ボ', 'bo')
    string = string.replace('パ', 'pa')
    string = string.replace('ピ', 'pi')
    string = string.replace('プ', 'pu')
    string = string.replace('ペ', 'pe')
    string = string.replace('ポ', 'po')
    string = string.replace('マ', 'ma')
    string = string.replace('ミ', 'mi')
    string = string.replace('ム', 'mu')
    string = string.replace('メ', 'me')
    string = string.replace('モ', 'mo')
    string = string.replace('ヤ', 'ya')
    string = string.replace('ユ', 'yu')
    string = string.replace('ヨ', 'yo')
    string = string.replace('ラ', 'ra')
    string = string.replace('リ', 'ri')
    string = string.replace('ル', 'ru')
    string = string.replace('レ', 're')
    string = string.replace('ロ', 'ro')
    string = string.replace('ワ', 'wa')
    string = string.replace('ヰ', 'wi')
    string = string.replace('ヱ', 'we')
    string = string.replace('ヲ', 'wo')
    string = string.replace('ン', 'nn')
    string = string.replace('ァ', 'xa')
    string = string.replace('ィ', 'xi')
    string = string.replace('ゥ', 'xu')
    string = string.replace('ェ', 'xe')
    string = string.replace('ォ', 'xo')
    string = string.replace('ャ', 'la')
    string = string.replace('ュ', 'lu')
    string = string.replace('ョ', 'lo')
    string = string.replace('ヮ', 'va')
    string = string.replace('ヵ', 'ka')
    string = string.replace('ヶ', 'ke')
    string = string.replace('ッ', 'xx')
    string = string.replace('・', '')
    return string

def parse_line(line: str):
    lineElements = line.split('\t')
    kanaDict = {}
    if lineElements[4].strip() == lineElements[0].strip():
        kanaDict[kana_to_rime_code(lineElements[0])] = [lineElements[4].strip()]
    else:
        kanaDict[kana_to_rime_code(lineElements[0])] = [lineElements[4].strip(), lineElements[0].strip()]
    return kanaDict


with open('./source/mozcdic-ut-20220423.txt', 'r') as file:
    line = file.readline()
    out = open('./out/mozcdic.txt', 'w')
    while line:
        kanaDict = parse_line(line)
        for code, wordList in kanaDict.items():
            for expresses in wordList:
                out.write(expresses + '\t' + code + '\n')
        line = file.readline()
    out.close()
